inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - '*/cache/**'
  RunRailsCops: true

Metrics/MethodLength:
  Description: 'Method has too many lines.'
  Enabled: false

Style/ParallelAssignment:
  Description: 'Do not use parallel assignment.'
  Enabled: false

Style/Documentation:
  Description: 'Missing top-level class documentation comment.'
  Enabled: false

Metrics/LineLength:
  Description: 'Line is too long.'
  Enabled: false

Rails/FindBy:
  Description: 'Prefer find_by over where.first.'
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

# This one reports false positives inside blocks/lambdas
Lint/NonLocalExitFromIterator:
  Description: 'Do not use return in iterator to cause non-local exit.'
  Enabled: false

Style/SingleLineBlockParams:
  Description: 'Name `reduce` block params `|a, e|`.'
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: 'slashes'
  AllowInnerSlashes: true
